Add web page endpoints for youtube channels
umputun/feed-master pull request #96
Opened 2022-10-23 18:24 UTC by orthur

Added `/yt/channels` and `/yt/channel/channelID` endpoints for web UI

![localhost_8087_yt_channel_UCTVk323gzizpujtn2T_BL7w (1)](https://user-images.githubusercontent.com/1266396/197409124-b10f233f-acc3-49f5-b3ac-a4367ec06897.png)

![localhost_8087_yt_channels](https://user-images.githubusercontent.com/1266396/197409132-8a5ebd8f-24fe-4b74-ab07-416e0486b4b2.png)

2022-10-23 18:32 UTC, umputun reviewed
thx, minor comment iussue only

2022-10-23 18:32 UTC, umputun commented on app/youtube/feed/feed.go
> +	DurationFmt string // used for ui only in
looks like you have a part of the comment missing

2022-10-23 18:35 UTC, umputun commented
confused a little bit. isn't this the same thing as the current /sources, i.e. https://feedmaster.umputun.com/feed/echo-msk/sources

2022-10-23 18:40 UTC, orthur commented
> confused a little bit. isn't this the same thing as the current /sources, i.e. https://feedmaster.umputun.com/feed/echo-msk/sources
> 
> upd: I meant the second picture

`/feed/feedName/sources` gets sources from `feeds:` field in `fm.yml`, but `/yt/channels` gets channels from `youtube` field

2022-10-23 19:07 UTC, umputun commented
but why we even care? channels from youtube struct don't represent the actual output, but rathee yt sources used to make feeds defineds in feeds.<name>.sources. The part user see is from this feeds section, not from youtube section

2022-10-23 19:13 UTC, orthur commented
I thought youtube section is separate thing for getting youtube audio and feeds section for other RSS podcasts. I use it without feeds section, hence I made web page to see which channels have set in youtube section

2022-10-23 19:23 UTC, umputun commented
well, youtube part is making feeds as well, however this is done just to provide sources for the primary section. The intended use case can be seen in the provided https://github.com/umputun/feed-master/blob/master/yt-test.yml 

As you can see feeds.yt-example.sources just using youtube.channels.

2022-10-23 19:33 UTC, orthur commented
Yes I got it. I am fine with closing this PR if changes is not needed

2022-10-23 21:11 UTC, umputun commented
I think the part of UI to show the actual list of items per channel is a useful one. It will be great if it can be adapted to work with sources. We also can replace the link from /sources to this one

2022-10-24 17:12 UTC, orthur commented
what do you mean to "work with sources"?

2022-10-24 17:22 UTC, umputun commented
Instead of youtube-specific /yt/channel/channelID the page should be for any source, i.e. smth like /feed/{name}/source/{src} which show the same page, but instead of making it from yt channel info, render it from the higher level feed info (i.e. `s.Conf.Feeds`)

2022-11-20 18:34 UTC, umputun commented
> what would be `{src}` value? `id: UCWAIvx2yYLK_xTYD4F2mUNw`?

the src is `feeds.{name}.sources.name` value, i.e. for the provided conf, it would be `Точка`, `Живой Гвоздь`, and so on

```yml
feeds:
  yt-example:
    title: Some cool channels
    description: an example of youtube-based podcast
    link: http://example.com
    language: "ru-ru"
    image: images/yt-example.png
    telegram_channel: udev_test
    sources:
      - name: Точка
        url: http://localhost:8080/yt/rss/PLZVQqcKxEn_6YaOniJmxATjODSVUbbMkd
      - name: Живой Гвоздь
        url: http://localhost:8080/yt/rss/UCWAIvx2yYLK_xTYD4F2mUNw
      - name: Дилетант
        url: http://localhost:8080/yt/rss/UCuIE7-5QzeAR6EdZXwDRwuQ
      - name: Сергей Асланян
        url: http://localhost:8080/yt/rss/UCPemWOA2UiBwhTauetmz95w
```

2022-11-20 18:36 UTC, umputun commented
note: you  last merge/rebase made this PR very confusing. I suggest to replace it on top of the current master or somehow squash. @paskal may know what git magic needed for this

2022-11-20 18:56 UTC, paskal commented
`git rebase upstream/master` is what you need to do in your branch.

2022-11-27 12:04 UTC, orthur commented
changed endpoint to `/feed/name/source/source`

2022-12-18 00:38 UTC, umputun requested changes
the link from /sources still points to the old place, it should be changed to the new url (i.e. source/blah) you have added

2022-12-19 19:58 UTC, umputun reviewed
LGTM. I would like to merge it but pls rebase it first and make a single (or a pair) of committs. If i squash it with github it will rewrite commit and set me as the author

2022-12-19 20:27 UTC, merged